# Generated by Django 3.1.4 on 2021-02-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_auto_20210214_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_features',
            name='idd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
