# Generated by Django 3.1.4 on 2021-02-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_home_features_idd'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision_pic', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('making_pic', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('sidebar_pic', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.RemoveField(
            model_name='home_features',
            name='idd',
        ),
    ]
