# Generated by Django 3.1.4 on 2021-02-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_auto_20210224_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home_features',
            old_name='photo',
            new_name='photo1',
        ),
        migrations.RenameField(
            model_name='home_features',
            old_name='tittle',
            new_name='title1',
        ),
        migrations.AddField(
            model_name='home_features',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='home_features',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='home_features',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='home_features',
            name='title2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home_features',
            name='title3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
