# Generated by Django 3.1.4 on 2021-02-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0006_auto_20210224_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_features',
            name='title4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
