# Generated by Django 3.1.4 on 2021-02-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0007_home_features_title4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('pic3', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('pic4', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
